export type PropertyDetails = {
  _id?: unknown;
  State: string;
  County: string;
  Address: string;
  "Parcel Number": string;
  "Principal Amount Owed": string;

  "Lender Name": string;
  "Lender Phone Number": string;

  "Law Firm Name": string;
  "Foreclosure Sale Date": string;
  ID: number;
  ADDRESS_FROM_BACKEND: string;
  ASSESSED_VALUE: string;
  ASSESSED_LAND_VALUE: string;
  ASSESSED_IMPROVEMENT_VALUE: string;
  MARKET_VALUE: string;
  MARKET_LAND_VALUE: string;
  MARKET_IMPROVEMENT_VALUE: string;
  TAX_AMOUNT: string;
  LAST_SALE_AMOUNT: string;
  ESTIMATED_VALUE: string;
  ESTIMATED_EQUITY: string;
  LOT_SQUARE_FEET: string;
  ASSESSMENT_YEAR: number;
  YEAR_BUILT: number;
  EFFECTIVE_YEAR_BUILT: number;
  PARKING_SPACES: number;
  PROPERTIES_OWNED: number;
  SQUARE_FEET: string;
  BEDROOMS: number;
  FULL_BATHROOMS: number;
  LATITUDE: number;
  LONGITUDE: number;
  BATHROOMS: number;
  STORIES: number;
  LOT_ACRES: number;
  LTV_RATIO: number;
  ITV_RATIO: number;
  GROSS_YIELD: number;
  OWNER_1_CORPORATE: boolean;
  MOBILE_HOME: boolean;
  TIMESHARE: boolean;
  CASH_BUYER: boolean;
  HOA_PRESENT: number;
  HOMESTEAD_EXEMPT: boolean;
  APN: string;
  APN_UNFORMATTED: string;
  COUNTY_USE_CODE: string;
  ZONING: string;
  CENSUS_TRACT: number;
  SCHOOL_DISCTRICT: string;
  TAX_JURISDICTION_CODE: number;
  JURISDICTION: string;
  SUBDIVISION: string;
  OWNER_1_FULL_NAME: string;
  OWNER_OCCUPANCY: string;
  PROPERTY_CLASS: string;
  LAND_USE: string;
  BUILDING_CONDITION: string;
  CONSTRUCTION_QUALITY: string;
  SEWER_TYPE: string;
  OWNERSHIP_TYPE: string;
  MAIL_ADDRESS_NUMBER: number;
  MAIL_ADDRESS_STREET: string;
  MAIL_ADDRESS_STREET_SUFFIX: string;
  MAIL_ADDRESS_POST_DIRECTION: string;
  MAIL_ADDRESS_ZIP: number;
  MAIL_ADDRESS_CITY: string;
  MAIL_ADDRESS_STATE: string;
  MORTGAGE_AMOUNT: string;
  MORTGAGE_INTEREST_RATE: string;
  TERM_TYPE: string;
  TERM: number;
  MORTGAGE_GRANTEE_NAME: string;
  MORTGAGE_POSITION: string;
  MORTGAGE_TYPE: string;
  TAX_YEAR_1: number;
  TAX_AMOUNT_1: string;
  ASSESSED_VALUE_1: string;
  TAX_AMOUNT_CHANGE_1: number;
  ASSESSED_VALUE_CHANGE_1: number;
  TAX_YEAR_2: number;
  TAX_AMOUNT_2: string;
  ASSESSED_VALUE_2: string;
  TAX_AMOUNT_CHANGE_2: number;
  ASSESSED_VALUE_CHANGE_2: number;
  TAX_YEAR_3: number;
  TAX_AMOUNT_3: string;
  ASSESSED_VALUE_3: string;
  TAX_AMOUNT_CHANGE_3: number;
  ASSESSED_VALUE_CHANGE_3: number;
  TAX_YEAR_4: number;
  TAX_AMOUNT_4: string;
  ASSESSED_VALUE_4: string;
  TAX_AMOUNT_CHANGE_4: number;
  ASSESSED_VALUE_CHANGE_4: number;
  TAX_YEAR_5: number;
  TAX_AMOUNT_5: string;
  ASSESSED_VALUE_5: string;
  TAX_AMOUNT_CHANGE_5: number;
  ASSESSED_VALUE_CHANGE_5: number;
  RECORDING_DATE_1: string;
  SALE_DATE_1: string;
  AMOUNT_1: string;
  DOCUMENT_NUMBER_1: string;
  DOCUMENT_TYPE_1: string;
  TRANSACTION_TYPE_1: string;
  BUYER_1: string;
  SELLER_1: string;
  PURCHASE_METHOD_1: string;
  RECORDING_DATE_2: string;
  SALE_DATE_2: string;
  DOCUMENT_TYPE_2: string;
  BUYER_2: string;
  RECORDING_DATE_3: string;
  SALE_DATE_3: string;
  AMOUNT_3: string;
  DOCUMENT_NUMBER_3: string;
  DOCUMENT_TYPE_3: string;
  TRANSACTION_TYPE_3: string;
  BUYER_3: string;
  SELLER_3: string;
  PURCHASE_METHOD_3: string;
  RECORDING_DATE_4: string;
  SALE_DATE_4: string;
  DOCUMENT_TYPE_4: string;
  TRANSACTION_TYPE_4: string;
  BUYER_4: string;
  SELLER_4: string;
  RECORDING_DATE_5: string;
  SALE_DATE_5: string;
  DOCUMENT_TYPE_5: string;
  TRANSACTION_TYPE_5: string;
  BUYER_5: string;
  SELLER_5: string;
  RECORDING_DATE_6: string;
  SALE_DATE_6: string;
  AMOUNT_6: string;
  DOCUMENT_TYPE_6: string;
  TRANSACTION_TYPE_6: string;
  BUYER_6: string;
  PURCHASE_METHOD_6: string;
  "Publication Name": string;
  Date: string;
  "Notice Identification": string;
  "Notice Content": string;
  County: string;

  "Date of Debt": string;

  "Borrower Name(s)": string;

  "Attorney Phone Number": string;
  "Foreclosure Sale Date": string;
  "Lender Phone": string;
  STORIES: number;
  "Opening Bid/Mortgage Balance": number;
  "Google Maps Image URL": string;
  "Google Earth Image URL": string;
};
