const mongoose = require("mongoose");

const propertySchema = new mongoose.Schema({
 
  Address: { type: String, index: true },
  ID: Number,
  ASSESSED_VALUE: Number,
  ASSESSED_LAND_VALUE: Number,
  ASSESSED_IMPROVEMENT_VALUE: Number,
  MARKET_VALUE: Number,
  MARKET_LAND_VALUE: Number,
  MARKET_IMPROVEMENT_VALUE: Number,
  TAX_AMOUNT: Number,
  ESTIMATED_VALUE: { type: Number, index: true },
  ESTIMATED_EQUITY: Number,
  LOT_SQUARE_FEET: Number,
  ASSESSMENT_YEAR: Number,
  "Year Built": { type: Number, index: true },
  PARKING_SPACES: Number,
  PROPERTIES_OWNED: Number,
  SQUARE_FEET: Number,
  BEDROOMS: Number,
  LATITUDE: Number,
  LONGITUDE: Number,
  BATHROOMS: Number,
  LOT_ACRES: Number,
  LTV_RATIO: Number,
  ITV_RATIO: Number,
  OWNER_1_CORPORATE: Boolean,
  MOBILE_HOME: Boolean,
  TIMESHARE: Boolean,
  CASH_BUYER: Boolean,
  HOA_PRESENT: Boolean,
  HOMESTEAD_EXEMPT: Boolean,
  APN: String,
  APN_UNFORMATTED: String,
  COUNTY_USE_CODE: String,
  ZONING: String,
  CENSUS_TRACT: Number,
  SCHOOL_DISCTRICT: String,
  TAX_JURISDICTION_CODE: Number,
  JURISDICTION: String,
  OWNER_1_FULL_NAME: String,
  OWNER_OCCUPANCY: String,
  PROPERTY_CLASS: { type: String, index: true },
  LAND_USE: String,
  OWNERSHIP_TYPE: { type: String, index: true },
  MAIL_ADDRESS_NUMBER: Number,
  MAIL_ADDRESS_STREET: String,
  MAIL_ADDRESS_STREET_SUFFIX: String,
  MAIL_ADDRESS_ZIP: Number,
  MAIL_ADDRESS_CITY: String,
  MAIL_ADDRESS_STATE: { type: String, index: true },
  MORTGAGE_AMOUNT: Number,
  MORTGAGE_INTEREST_RATE: Number,
  MORTGAGE_GRANTEE_NAME: String,
  MORTGAGE_POSITION: String,
  MORTGAGE_TYPE: String,
  TAX_YEAR_1: Number,
  TAX_AMOUNT_1: Number,
  ASSESSED_VALUE_1: Number,
  TAX_AMOUNT_CHANGE_1: Number,
  ASSESSED_VALUE_CHANGE_1: Number,
  TAX_YEAR_2: Number,
  TAX_AMOUNT_2: Number,
  ASSESSED_VALUE_2: Number,
  TAX_AMOUNT_CHANGE_2: Number,
  ASSESSED_VALUE_CHANGE_2: Number,
  TAX_YEAR_3: Number,
  TAX_AMOUNT_3: Number,
  ASSESSED_VALUE_3: Number,
  TAX_AMOUNT_CHANGE_3: Number,
  ASSESSED_VALUE_CHANGE_3: Number,
  TAX_YEAR_4: Number,
  TAX_AMOUNT_4: Number,
  ASSESSED_VALUE_4: Number,
  TAX_AMOUNT_CHANGE_4: Number,
  ASSESSED_VALUE_CHANGE_4: Number,
  TAX_YEAR_5: Number,
  TAX_AMOUNT_5: Number,
  ASSESSED_VALUE_5: Number,
  TAX_AMOUNT_CHANGE_5: Number,
  ASSESSED_VALUE_CHANGE_5: Number,
  RECORDING_DATE_1: {
    $numberLong: String,
  },
  SALE_DATE_1: {
    $numberLong: String,
  },
  DOCUMENT_TYPE_1: String,
  TRANSACTION_TYPE_1: String,
  BUYER_1: String,
  RECORDING_DATE_2: {
    $numberLong: String,
  },
  SALE_DATE_2: {
    $numberLong: String,
  },
  DOCUMENT_TYPE_2: String,
  BUYER_2: String,
  RECORDING_DATE_3: {
    $numberLong: String,
  },
  SALE_DATE_3: {
    $numberLong: String,
  },
  AMOUNT_3: Number,
  DOCUMENT_NUMBER_3: String,
  DOCUMENT_TYPE_3: String,
  TRANSACTION_TYPE_3: String,
  BUYER_3: String,
  SELLER_3: String,
  PURCHASE_METHOD_3: String,
  RECORDING_DATE_4: {
    $numberLong: String,
  },
  SALE_DATE_4: {
    $numberLong: String,
  },
  DOCUMENT_TYPE_4: String,
  TRANSACTION_TYPE_4: String,
  BUYER_4: String,
  SELLER_4: String,
  RECORDING_DATE_5: {
    $numberLong: String,
  },
  SALE_DATE_5: {
    $numberLong: String,
  },
  DOCUMENT_TYPE_5: String,
  TRANSACTION_TYPE_5: String,
  BUYER_5: String,
  SELLER_5: String,
  RECORDING_DATE_6: {
    $numberLong: String,
  },
  SALE_DATE_6: {
    $numberLong: String,
  },
  AMOUNT_6: Number,
  DOCUMENT_TYPE_6: String,
  TRANSACTION_TYPE_6: String,
  BUYER_6: String,
  PURCHASE_METHOD_6: String,
  "Publication Name": String,
  Date: String,
  "Notice Identification": String,
  "Notice Content": String,
  County: { type: String, index: true },

  "Parcel Number": String,
  "Principal Amount Owed": Number,
  "Date of Debt": String,
  "Lender Name": String,
  "Borrower Name(s)": String,
  "Law Firm Name": String,
  "Attorney Phone Number": String,
  "Foreclosure Sale Date": String,
});

const Properties = mongoose.model("Properties", propertySchema);
export default Properties;
